# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: aksharagyana
      name: aksharagyana/animated-robot
      ref: refs/heads/main


trigger:
  branches:
    include:
      - feature/*
      - bugfix/*
      - hotfix/*
      - release/*
      - main

extends:
  template: tf-pipeline.yml@templates
  parameters:
#    tfModulePath: "s"
    azServiceConnection: "scncwdev"
    tfStateAzSaRG: "saroottf"
    tfStateAzSa: "sacwtfstate"
    tfStateAzSaCont: "tfstate"
    envInstallList:
      - workspace: devlevel0
        tfvars: custom.tfvars
      - workspace: devenv-level0
        tfvars: custom.tfvars





