# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.7.5'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendAzureRmContainerName: 'env-businessfunname'
    backendAzureRmKey: 'terraform.tfstate'
    backendAzureRmResourceGroupName: 'env-sa-rg-name'
    backendAzureRmStorageAccountName: 'env-sa-name'
    backendServiceArm: 'ServiceConnectionName'
    

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'ServiceConnectionName'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'ServiceConnectionName'


