# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: aksharagyana
      name: aksharagyana/animated-robot
      ref: refs/heads/main


trigger:
  branches:
    include:
      - feature/*
      - bugfix/*
      - hotfix/*
      - release/*
      - main

extends:
  template: tf-pipeline.yml@templates
  parameters:
    tfvars: "custom.tfvars"
#    tfModulePath: "s"
    azServiceConnection: "scncwdev"
    tfStateAzSaRG: "saroottf"
    tfStateAzSa: "sacwtfstate"
    tfStateAzSaCont: "tfstate"
    tfworkspace:
      - "devlevel0"





